name: Deploy Hugo Site
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Fetch submodules
        run: git submodule update --init --recursive
      - name: List repository contents
        run: ls -la
      - name: Check theme directory
        run: ls -la themes || echo "themes directory not found"
      - name: Check content directory
        run: ls -la content || echo "content directory not found"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.147.0'
          extended: true
      - name: Check Hugo version
        run: hugo version
      - name: Build Hugo site
        run: hugo --minify -D --verbose
      - name: List public folder contents
        run: ls -la public || echo "public folder not found"
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
          cname: mahima.blog